# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.10
      uses: actions/setup-python@main
      with:
        python-version: "3.10"
    - run: |
        set -x
        python -m pip install --upgrade pip pipenv
        PIPENV_VENV_IN_PROJECT=1 PIPENV_VERBOSITY=10 pipenv install --categories test
        PIPENV_VENV_IN_PROJECT=1 PIPENV_VERBOSITY=10 pipenv install --system --categories test
        PIPENV_VENV_IN_PROJECT=1 PIPENV_VERBOSITY=10 pipenv install --system --categories packages
        pytest
